language: csharp
solution: Todoozy.sln
install:
  - nuget restore Todoozy.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Todoozy.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.exe ./tests/Todoozy.Tests/bin/Release/Todoozy.Tests.dll